#!/usr/bin/env bash
# ==============================================================================
#  localai.sh — Local AI Environment Manager
#  Version : 1.0.0
#  Author  : wamuufan
#  License : BSD 2-Clause
#
#  Manages isolated, modular AI development & runtime environments
#  using Podman and Distrobox.
#
#  USAGE:
#    localai.sh container new <name>
#    localai.sh container list
#    localai.sh container rm <name>
#    localai.sh install <container> <tool>
#    localai.sh start   <container> <tool>
#    localai.sh stop    <container> <tool>
#    localai.sh shell   <container>
#    localai.sh doctor
# ==============================================================================

set -euo pipefail

# ------------------------------------------------------------------------------
# GLOBAL CONSTANTS
# ------------------------------------------------------------------------------
readonly SCRIPT_VERSION="1.0.0"
readonly BASE_DIR="${HOME}/.local/containers"
readonly BASE_IMAGE="docker.io/library/ubuntu:26.04"

# PID file path helper (inside the container's home so host can read it)
pid_file() {
    local container="$1" tool="$2"
    echo "${BASE_DIR}/${container}/.run/${tool}.pid"
}

# ------------------------------------------------------------------------------
# COLOUR & LOGGING HELPERS
# ------------------------------------------------------------------------------
if [[ -t 1 ]]; then
    RED=$'\033[0;31m'
    GREEN=$'\033[0;32m'
    YELLOW=$'\033[1;33m'
    CYAN=$'\033[0;36m'
    BOLD=$'\033[1m'
    DIM=$'\033[2m'
    RESET=$'\033[0m'
else
    RED='' GREEN='' YELLOW='' CYAN='' BOLD='' DIM='' RESET=''
fi

log_info()    { printf "${CYAN}[INFO]${RESET}    %s\n"    "$*"; }
log_success() { printf "${GREEN}[SUCCESS]${RESET} %s\n"   "$*"; }
log_warn()    { printf "${YELLOW}[WARN]${RESET}    %s\n"  "$*"; }
log_error()   { printf "${RED}[ERROR]${RESET}   %s\n"     "$*" >&2; }
log_step()    { printf "${BOLD}${CYAN} ──▶${RESET} %s\n"  "$*"; }
log_header()  {
    printf "\n${BOLD}${CYAN}%s${RESET}\n" "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${BOLD}  %s${RESET}\n"         "$*"
    printf "${BOLD}${CYAN}%s${RESET}\n\n"  "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

die() {
    log_error "$*"
    exit 1
}

# ------------------------------------------------------------------------------
# PREREQUISITE CHECKS
# ------------------------------------------------------------------------------
require_cmd() {
    local cmd="$1"
    command -v "$cmd" &>/dev/null
}

check_container_exists() {
    local name="$1"
    distrobox list --no-color 2>/dev/null | awk '{print $3}' | grep -qx "$name"
}

assert_container_exists() {
    local name="$1"
    check_container_exists "$name" \
        || die "Container '${name}' not found. Create it first: localai.sh container new ${name}"
}

# ------------------------------------------------------------------------------
# TOOL REGISTRY
#
# To add a new tool:
#   1. Implement install_<toolname>()
#   2. Implement start_<toolname>()
#   3. Implement stop_<toolname>()
#   4. Add the tool name to SUPPORTED_TOOLS below
# ------------------------------------------------------------------------------

# ── OLLAMA ──────────────────────────────────────────────────────────────────
install_ollama() {
    local container="$1"
    local home_dir="${BASE_DIR}/${container}"

    log_header "Installing Ollama → ${container}"

    log_step "Updating package lists..."
    distrobox enter "${container}" -- bash -c "
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update -qq
        sudo apt-get install -y -qq curl ca-certificates
    "

    log_step "Downloading and running official Ollama installer..."
    distrobox enter "${container}" -- bash -c "
        set -e
        if command -v ollama &>/dev/null; then
            echo 'Ollama is already installed, skipping.'
            ollama --version
            exit 0
        fi
        curl -fsSL https://ollama.com/install.sh | sh
    "

    mkdir -p "${home_dir}/.ollama/models"

    log_step "Configuring Ollama data directory..."
    cat > "${home_dir}/.ollama/ollama.env" <<EOF
# Ollama runtime environment — auto-generated by localai.sh
export OLLAMA_HOME="${home_dir}/.ollama"
export OLLAMA_MODELS="${home_dir}/.ollama/models"
export OLLAMA_HOST="0.0.0.0:11434"
EOF

    log_success "Ollama installed successfully in '${container}'."
    log_info    "Data directory : ${home_dir}/.ollama"
    log_info    "Pull a model   : localai.sh shell ${container}  →  ollama pull llama3.2"
}

# ── SERVICE CONTROL HELPERS ──────────────────────────────────────────────────
check_and_clean_pid() {
    local container="$1"
    local pid_f="$2"
    local tool_name="$3"

    if [[ -f "${pid_f}" ]]; then
        local old_pid; old_pid="$(cat "${pid_f}")"
        if distrobox enter "${container}" -- bash -c "kill -0 '${old_pid}'" 2>/dev/null; then
            log_warn "${tool_name} is already running (PID ${old_pid}) in '${container}'."
            return 1
        else
            log_info "Stale PID file found, cleaning up..."
            rm -f "${pid_f}"
        fi
    fi
    return 0
}

stop_service_in_container() {
    local container="$1"
    local tool_name="$2"
    local timeout="${3:-10}"
    local pid_f; pid_f="$(pid_file "${container}" "${tool_name}")"

    if [[ ! -f "${pid_f}" ]]; then
        log_warn "No PID file found for ${tool_name} in '${container}'. Is it running?"
        return 0
    fi

    local pid; pid="$(cat "${pid_f}")"
    log_step "Stopping ${tool_name} (PID ${pid}) in '${container}'..."

    distrobox enter "${container}" -- bash -c "
        if kill -0 '${pid}' 2>/dev/null; then
            kill -TERM '${pid}'
            echo 'Sent SIGTERM to ${tool_name}.'
            for i in \$(seq 1 ${timeout}); do
                kill -0 '${pid}' 2>/dev/null || { echo '${tool_name} stopped gracefully.'; exit 0; }
                sleep 1
            done
            kill -KILL '${pid}' 2>/dev/null && echo 'Forced kill after timeout.'
        else
            echo '${tool_name} process not running.'
        fi
    " || true

    rm -f "${pid_f}"
    log_success "${tool_name} stopped."
}

start_ollama() {
    local container="$1"
    local home_dir="${BASE_DIR}/${container}"
    local pid_f;  pid_f="$(pid_file "${container}" "ollama")"
    local log_f="${home_dir}/.run/ollama.log"

    mkdir -p "${home_dir}/.run"

    check_and_clean_pid "${container}" "${pid_f}" "Ollama" || return 0

    log_step "Starting Ollama in '${container}' (background)..."
    distrobox enter "${container}" -- bash -c "
        source '${home_dir}/.ollama/ollama.env' 2>/dev/null || true
        nohup ollama serve > '${log_f}' 2>&1 &
        echo \$! > '${pid_f}'
        echo \"Ollama started with PID \$(cat '${pid_f}')\"
    "

    sleep 1
    if [[ -f "${pid_f}" ]]; then
        local pid; pid="$(cat "${pid_f}")"
        log_success "Ollama started (PID ${pid}). API: http://localhost:11434"
        log_info    "Logs: ${log_f}"
    else
        log_error "Ollama may not have started. Check logs: ${log_f}"
    fi
}

stop_ollama() {
    stop_service_in_container "$1" "ollama" 10
}

# ── COMFYUI ─────────────────────────────────────────────────────────────────
install_comfyui() {
    local container="$1"
    local home_dir="${BASE_DIR}/${container}"
    local comfy_dir="${home_dir}/comfyui"

    log_header "Installing ComfyUI → ${container}"

    log_step "Installing system dependencies..."
    distrobox enter "${container}" -- bash -c "
        set -e
        export DEBIAN_FRONTEND=noninteractive
        # Add Ubuntu 24.04 (Noble) repository directly to the isolated ubuntu.sources
        cat <<'EOF' | sudo tee -a /etc/apt/sources.list.d/ubuntu.sources > /dev/null

Types: deb
URIs: http://archive.ubuntu.com/ubuntu/
Suites: noble
Components: main universe
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
EOF
        
        # Pin python3.12 packages to Noble, and ignore everything else from Noble
        cat <<'EOF' | sudo tee /etc/apt/preferences.d/99-noble-python > /dev/null
Package: *python3.12*
Pin: release n=noble
Pin-Priority: 900

Package: *
Pin: release n=noble
Pin-Priority: -10
EOF


        sudo apt-get update -qq
        sudo apt-get install -y -qq \
            python3.12 python3.12-venv python3.12-dev python3-pip \
            git curl ca-certificates \
            libgl1 libglib2.0-0 libsm6 libxext6 libxrender-dev \
            ffmpeg
    "

    log_step "Cloning ComfyUI repository..."
    distrobox enter "${container}" -- bash -c "
        set -e
        if [[ -d '${comfy_dir}' && -f '${comfy_dir}/main.py' ]]; then
            echo 'ComfyUI already exists, pulling latest changes...'
            git -C '${comfy_dir}' pull --ff-only
        else
            git clone --depth=1 https://github.com/comfyanonymous/ComfyUI.git '${comfy_dir}'
        fi
    "

    log_step "Creating Python virtual environment..."
    distrobox enter "${container}" -- bash -c "
        set -e
        if [[ ! -d '${comfy_dir}/.venv' ]]; then
            python3.12 -m venv '${comfy_dir}/.venv'
        fi
    "

    log_step "Installing Python dependencies (this may take a while)..."
    distrobox enter "${container}" -- bash -c "
        set -e
        source '${comfy_dir}/.venv/bin/activate'
        if command -v nvidia-smi &>/dev/null 2>&1; then
            echo 'NVIDIA GPU detected — installing PyTorch with CUDA support...'
            pip install --upgrade pip
            pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
        else
            echo 'No NVIDIA GPU detected — installing CPU-only PyTorch...'
            pip install --upgrade pip
            pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        fi
        pip install -r '${comfy_dir}/requirements.txt'
    "

    mkdir -p \
        "${comfy_dir}/models/checkpoints" \
        "${comfy_dir}/models/loras" \
        "${comfy_dir}/models/vae" \
        "${comfy_dir}/models/controlnet" \
        "${comfy_dir}/models/clip" \
        "${comfy_dir}/output" \
        "${comfy_dir}/input" \
        "${comfy_dir}/custom_nodes" \
        "${home_dir}/.run"

    cat > "${home_dir}/.comfyui.env" <<EOF
# ComfyUI runtime environment — auto-generated by localai.sh
export COMFYUI_DIR="${comfy_dir}"
export COMFYUI_VENV="${comfy_dir}/.venv"
export COMFYUI_HOST="0.0.0.0"
export COMFYUI_PORT="8188"
EOF

    log_success "ComfyUI installed successfully in '${container}'."
    log_info    "App directory  : ${comfy_dir}"
    log_info    "Models folder  : ${comfy_dir}/models/checkpoints/"
    log_info    "Web UI         : http://localhost:8188  (after start)"
}

start_comfyui() {
    local container="$1"
    local home_dir="${BASE_DIR}/${container}"
    local pid_f;  pid_f="$(pid_file "${container}" "comfyui")"
    local log_f="${home_dir}/.run/comfyui.log"

    mkdir -p "${home_dir}/.run"

    check_and_clean_pid "${container}" "${pid_f}" "ComfyUI" || return 0

    log_step "Starting ComfyUI in '${container}' (background)..."
    distrobox enter "${container}" -- bash -c "
        set -e
        source '${home_dir}/.comfyui.env' 2>/dev/null || true
        source \"\${COMFYUI_VENV}/bin/activate\"
        nohup python3 \"\${COMFYUI_DIR}/main.py\" \
            --listen \"\${COMFYUI_HOST}\" \
            --port \"\${COMFYUI_PORT}\" \
            > '${log_f}' 2>&1 &
        echo \$! > '${pid_f}'
        echo \"ComfyUI started with PID \$(cat '${pid_f}')\"
    "

    sleep 2
    if [[ -f "${pid_f}" ]]; then
        local pid; pid="$(cat "${pid_f}")"
        log_success "ComfyUI started (PID ${pid}). Web UI: http://localhost:8188"
        log_info    "Logs: ${log_f}"
    else
        log_error "ComfyUI may not have started. Check logs: ${log_f}"
    fi
}

stop_comfyui() {
    stop_service_in_container "$1" "comfyui" 15
}

# ==============================================================================
# ▼▼▼  ADD NEW TOOLS HERE  ▼▼▼
#
# Follow this pattern for each new tool:
#
#   install_<toolname>() { ... }   # idempotent setup inside the container
#   start_<toolname>()   { ... }   # background launch + PID file
#   stop_<toolname>()    { ... }   # graceful SIGTERM → SIGKILL
#
# Then add the name to SUPPORTED_TOOLS below.
# ==============================================================================

readonly SUPPORTED_TOOLS=("ollama" "comfyui")

tool_is_supported() {
    local tool="$1"
    [[ " ${SUPPORTED_TOOLS[*]} " =~ " ${tool} " ]]
}

# ------------------------------------------------------------------------------
# COMMAND: container new
# ------------------------------------------------------------------------------
cmd_container_new() {
    local name="${1:?Usage: localai.sh container new <name>}"
    local home_dir="${BASE_DIR}/${name}"

    log_header "Creating container: ${name}"

    if check_container_exists "${name}"; then
        log_warn "Container '${name}' already exists. Skipping creation."
        return 0
    fi

    log_step "Creating isolated home directory: ${home_dir}"
    mkdir -p "${home_dir}"

    log_step "Creating Distrobox container (Ubuntu 26.04)..."
    distrobox create \
        --name      "${name}" \
        --image     "${BASE_IMAGE}" \
        --home      "${home_dir}" \
        --nvidia \
        --pre-init-hooks "printf 'Dir::Etc::sourcelist \"/etc/apt/sources.list.d/ubuntu.sources\";\nDir::Etc::sourceparts \"/dev/null\";\n' > /etc/apt/apt.conf.d/99-isolate-ubuntu.conf" \
        --yes

    log_step "Initialising container and installing base packages..."
    distrobox enter "${name}" -- bash -c "
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update -qq
        sudo apt-get upgrade -y -qq
        sudo apt-get install -y -qq \
            python3 python3-pip python3-venv \
            git curl wget ca-certificates \
            build-essential software-properties-common \
            htop nano less
    "

    log_success "Container '${name}' is ready."
    log_info    "Home directory : ${home_dir}"
    log_info    "Enter shell    : localai.sh shell ${name}"
    log_info    "Install a tool : localai.sh install ${name} <tool>"
}

# ------------------------------------------------------------------------------
# COMMAND: container list
# ------------------------------------------------------------------------------
cmd_container_list() {
    log_header "LocalAI Containers"

    if ! require_cmd distrobox; then
        die "distrobox not found. Run: localai.sh doctor"
    fi

    local raw
    raw="$(distrobox list --no-color 2>/dev/null | awk 'NR>1 {
        print $3 "|" $5 "|" $7
    }')" || true

    if [[ -z "$raw" ]]; then
        log_info "No containers found."
        return 0
    fi

    printf "${BOLD}%-28s %-14s %-10s %-s${RESET}\n" "NAME" "STATUS" "DATA DIR" "IMAGE"
    printf "${DIM}%s${RESET}\n" "────────────────────────────────────────────────────────────────────────────────"

    while IFS='|' read -r name status image; do
        [[ -z "$name" ]] && continue

        local data_dir="${BASE_DIR}/${name}"
        local data_label="✗ missing"
        [[ -d "$data_dir" ]] && data_label="✓ exists"

        local status_color="${GREEN}"
        [[ "$status" != "Up" ]] && status_color="${DIM}"

        printf "${status_color}%-28s${RESET} %-14s %-10s %-s\n" \
            "$name" "$status" "$data_label" "$image"
    done <<< "$raw"

    printf "\n${DIM}Tip: data dirs are never deleted by 'container rm'${RESET}\n\n"
}

# ------------------------------------------------------------------------------
# COMMAND: container rm
# ------------------------------------------------------------------------------
cmd_container_rm() {
    local name="${1:?Usage: localai.sh container rm <name>}"
    local home_dir="${BASE_DIR}/${name}"

    log_header "Removing container: ${name}"
    assert_container_exists "${name}"

    log_warn "This will REMOVE the container but KEEP all data in:"
    log_warn "  ${home_dir}"
    printf "${YELLOW}Proceed? [y/N]: ${RESET}"
    read -r answer
    [[ "${answer,,}" =~ ^y ]] || { log_info "Aborted."; return 0; }

    log_step "Removing container '${name}'..."
    distrobox rm --force "${name}"

    log_success "Container '${name}' removed."
    log_info    "Data preserved at : ${home_dir}"
    log_info    "To restore        : localai.sh container new ${name}"
}

# ------------------------------------------------------------------------------
# COMMAND: install
# ------------------------------------------------------------------------------
cmd_install() {
    local container="${1:?Usage: localai.sh install <container> <tool>}"
    local tool="${2:?Usage: localai.sh install <container> <tool>}"

    assert_container_exists "${container}"

    if ! tool_is_supported "${tool}"; then
        log_error "Unknown tool: '${tool}'"
        log_info  "Supported tools: ${SUPPORTED_TOOLS[*]}"
        exit 1
    fi

    "install_${tool}" "${container}"
}

# ------------------------------------------------------------------------------
# COMMAND: start
# ------------------------------------------------------------------------------
cmd_start() {
    local container="${1:?Usage: localai.sh start <container> <tool>}"
    local tool="${2:?Usage: localai.sh start <container> <tool>}"

    assert_container_exists "${container}"

    if ! tool_is_supported "${tool}"; then
        log_error "Unknown tool: '${tool}'"
        log_info  "Supported tools: ${SUPPORTED_TOOLS[*]}"
        exit 1
    fi

    "start_${tool}" "${container}"
}

# ------------------------------------------------------------------------------
# COMMAND: stop
# ------------------------------------------------------------------------------
cmd_stop() {
    local container="${1:?Usage: localai.sh stop <container> <tool>}"
    local tool="${2:?Usage: localai.sh stop <container> <tool>}"

    assert_container_exists "${container}"

    if ! tool_is_supported "${tool}"; then
        log_error "Unknown tool: '${tool}'"
        log_info  "Supported tools: ${SUPPORTED_TOOLS[*]}"
        exit 1
    fi

    "stop_${tool}" "${container}"
}

# ------------------------------------------------------------------------------
# COMMAND: shell
# ------------------------------------------------------------------------------
cmd_shell() {
    local container="${1:?Usage: localai.sh shell <container>}"
    assert_container_exists "${container}"
    log_info "Entering '${container}' — type 'exit' to return to host."
    distrobox enter "${container}"
}

# ------------------------------------------------------------------------------
# COMMAND: doctor
# ------------------------------------------------------------------------------
cmd_doctor() {
    log_header "LocalAI System Doctor v${SCRIPT_VERSION}"

    local all_ok=true

    check_dep() {
        local cmd="$1"
        local label="${2:-$cmd}"
        local hint="${3:-}"
        printf "  %-22s " "${label}:"
        if require_cmd "${cmd}"; then
            local ver; ver="$("${cmd}" --version 2>&1 | head -1)" || ver="(version unknown)"
            printf "${GREEN}✓ found${RESET}  ${DIM}%s${RESET}\n" "${ver}"
        else
            printf "${RED}✗ not found${RESET}"
            [[ -n "${hint}" ]] && printf "  ${DIM}→ %s${RESET}" "${hint}"
            printf "\n"
            all_ok=false
        fi
    }

    printf "${BOLD}Core dependencies:${RESET}\n"
    check_dep "podman"    "Podman"          "dnf install podman  /  apt install podman"
    check_dep "distrobox" "Distrobox"       "curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh"
    check_dep "git"       "Git"             "apt install git"
    check_dep "curl"      "curl"            "apt install curl"

    printf "\n${BOLD}Optional / GPU:${RESET}\n"
    check_dep "nvidia-smi" "nvidia-smi (GPU)"  "Install NVIDIA drivers + Container Toolkit"
    check_dep "nvcc"       "nvcc (CUDA)"        "Install CUDA toolkit"

    printf "\n${BOLD}Base directory:${RESET}\n"
    printf "  %-22s " "~/.local/containers:"
    if [[ -d "${BASE_DIR}" ]]; then
        printf "${GREEN}✓ exists${RESET}  ${DIM}%s${RESET}\n" "${BASE_DIR}"
    else
        printf "${YELLOW}⚠ missing${RESET}  ${DIM}(created automatically on first use)${RESET}\n"
    fi

    printf "\n${BOLD}Distrobox containers:${RESET}\n"
    if require_cmd distrobox; then
        local count
        count="$(distrobox list --no-color 2>/dev/null | awk 'NR>1 && NF>0 {c++} END {print c+0}')"
        printf "  %-22s ${CYAN}%s${RESET}\n" "Total containers:" "${count}"
    else
        printf "  ${DIM}(distrobox not available)${RESET}\n"
    fi

    printf "\n"
    if "${all_ok}"; then
        log_success "All core dependencies satisfied. System is ready."
    else
        log_warn    "Some dependencies are missing. Install them and re-run: localai.sh doctor"
        exit 1
    fi
}

# ------------------------------------------------------------------------------
# HELP / USAGE
# ------------------------------------------------------------------------------
cmd_help() {
    cat <<EOF

${BOLD}${CYAN}localai.sh${RESET} — Local AI Environment Manager ${DIM}v${SCRIPT_VERSION}${RESET}

${BOLD}USAGE${RESET}
  localai.sh <command> [arguments]

${BOLD}COMMANDS${RESET}

  ${CYAN}container new   <name>${RESET}
      Create a new Ubuntu 26.04 Distrobox container with an isolated home
      directory at ~/.local/containers/<name>. NVIDIA passthrough enabled.

  ${CYAN}container list${RESET}
      List all containers and their data-directory status.

  ${CYAN}container rm    <name>${RESET}
      Remove a container (distrobox rm). Data directory is NEVER deleted.

  ${CYAN}install  <container> <tool>${RESET}
      Install a tool inside a container (idempotent / safe to re-run).
      Supported tools: ${SUPPORTED_TOOLS[*]}

  ${CYAN}start    <container> <tool>${RESET}
      Start a tool in the background inside the container.
      Prevents double-start via PID file check.

  ${CYAN}stop     <container> <tool>${RESET}
      Gracefully stop a running tool (SIGTERM → SIGKILL after timeout).

  ${CYAN}shell    <container>${RESET}
      Open an interactive shell inside the specified container.

  ${CYAN}doctor${RESET}
      Check host system for required and optional dependencies.

EOF
}

# ------------------------------------------------------------------------------
# MAIN DISPATCHER
# ------------------------------------------------------------------------------
main() {
    local cmd="${1:-help}"
    shift || true

    case "${cmd}" in
        container)
            local sub="${1:-}"
            shift || true
            case "${sub}" in
                new)    cmd_container_new  "$@" ;;
                list)   cmd_container_list      ;;
                rm)     cmd_container_rm    "$@" ;;
                *)
                    log_error "Unknown container sub-command: '${sub}'"
                    log_info  "Usage: localai.sh container {new|list|rm} [args]"
                    exit 1
                    ;;
            esac
            ;;
        install)  cmd_install  "$@" ;;
        start)    cmd_start    "$@" ;;
        stop)     cmd_stop     "$@" ;;
        shell)    cmd_shell    "$@" ;;
        doctor)   cmd_doctor        ;;
        help|-h|--help) cmd_help    ;;
        *)
            log_error "Unknown command: '${cmd}'"
            cmd_help
            exit 1
            ;;
    esac
}

main "$@"
